version: "3"
volumes:
  postgres-data:
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      APP_DATABASE_URL: "${APP_DATABASE_URL}"
      RACK_ENV: "${RACK_ENV}"
      APP_SESSION_SECRET: "${APP_SESSION_SECRET}"
